export const STEP = {
	FRAME_TYPE: 'FRAME_TYPE',
	FRAME_FINISH: 'FRAME_FINISH',
	WHEELS: 'WHEELS',
	RIM_COLOR: 'RIM_COLOR',
	CHAIN: 'CHAIN',
} as const;

export const FRAME_TYPE_OPTION = {
	FULL_SUSPENSION: 'FULL_SUSPENSION',
	DIAMOND: 'DIAMOND',
	STEP_THROUGH: 'STEP_THROUGH',
} as const;

export const FRAME_FINISH_OPTION = {
	MATTE: 'MATTE',
	SHINY: 'SHINY',
} as const;

export const WHEELS_TYPE_OPTION = {
	ROAD: 'ROAD',
	MOUNTAIN: 'MOUNTAIN',
	FAT_BIKE: 'FAT_BIKE',
} as const;

export const RIM_COLOR_TYPE_OPTION = {
	RED: 'RED',
	BLACK: 'BLACK',
	BLUE: 'BLUE',
} as const;

export const CHAIN_TYPE_OPTION = {
	SINGLE: 'SINGLE',
	EIGHT: 'EIGHT_SPEED',
} as const;

export const frameTypesOptions = [FRAME_TYPE_OPTION.FULL_SUSPENSION, FRAME_TYPE_OPTION.DIAMOND, FRAME_TYPE_OPTION.STEP_THROUGH]
export const frameFinishOptions = [FRAME_FINISH_OPTION.MATTE, FRAME_FINISH_OPTION.SHINY];
export const wheelsOptions = [WHEELS_TYPE_OPTION.MOUNTAIN, WHEELS_TYPE_OPTION.ROAD, WHEELS_TYPE_OPTION.FAT_BIKE];
export const rimColorOptions = [RIM_COLOR_TYPE_OPTION.BLACK, RIM_COLOR_TYPE_OPTION.BLUE, RIM_COLOR_TYPE_OPTION.RED];
export const chainOptions = [CHAIN_TYPE_OPTION.EIGHT, CHAIN_TYPE_OPTION.SINGLE];

